spring:
  application:
    name: Digital Invoice Processing System

  datasource:
    url: jdbc:postgresql://postgres:5432/invoice_db
    username: invoice_user
    password: secret123
    driver-class-name: org.postgresql.Driver
