spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    default-schema: users
    liquibase-schema: public
    drop-first: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

integration:
  service:
    url: http://localhost:8084