server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: true
    default-schema: invoice
    liquibase-schema: public
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

user:
  service:
    url: http://localhost:8080
