server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false
    default-schema: invoice
    liquibase-schema: public

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

user:
  service:
    url: http://localhost:8080