server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: true
    default-schema: invoice
    liquibase-schema: public
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

user:
  service:
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /api/DIPS/api-docs
  swagger-ui:
    path: /api/DIPS/swagger-ui.html
